#!/bin/sh

CP=funcunit/java/selenium-java-client-driver.jar:steal/rhino/js.jar
ARGS=[
for arg
do
  if [ $arg != $0 ]
  then
    ARGS=$ARGS"'$arg'",
  fi
done
ARGS=$ARGS"'funcunit/'"]
java -Xss1024k -cp $CP org.mozilla.javascript.tools.shell.Main -e _args=$ARGS -opt -1 -e 'load('"'"funcunit/scripts/run.js"'"')'
